services:
  app:
    container_name: library
    build:
      context: .
#    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:80"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn library_system.wsgi:application --bind 0.0.0.0:80 --workers 3"
    networks:
      - library-network
    volumes:
      - ./:/app/
    ports:
      - "8000:80"

networks:
  library-network:
    name: library-network
